import './globals.css'

import { Inter, Poppins } from 'next/font/google'

import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import Navbar from '@/components/Navbar';

const poppins = Poppins({
  weight: ["600"],
  subsets:[ "latin"]
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider   >
    <html lang="en">
      <body className={poppins.className}>
      <Navbar/>
        {children}
        </body>
    </html>
    </ClerkProvider>
  )
}
